### ISSUE TITLE
tensor shape mismatch when training on 24khz LibriTTS dataset

### ISSUE THREAD

**Issue by ZhikangNiu** [descriptinc/descript-audio-codec#58]
Traceback (most recent call last):
  File "/home/v-zhikangniu/descript-audio-codec/scripts/train.py", line 441, in <module>
    train(args, accel)
  File "/home/v-zhikangniu/miniconda3/envs/dac/lib/python3.9/site-packages/argbind/argbind.py", line 159, in cmd_func
    return func(*cmd_args, **kwargs)
  File "/home/v-zhikangniu/descript-audio-codec/scripts/train.py", line 425, in train
    validate(state, val_dataloader, accel)
  File "/home/v-zhikangniu/miniconda3/envs/dac/lib/python3.9/site-packages/audiotools/ml/decorators.py", line 375, in decorated
    output = fn(*args, **kwargs)
  File "/home/v-zhikangniu/descript-audio-codec/scripts/train.py", line 344, in validate
    output = val_loop(batch, state, accel)
  File "/home/v-zhikangniu/miniconda3/envs/dac/lib/python3.9/site-packages/audiotools/ml/decorators.py", line 321, in decorated
    output = fn(*args, **kwargs)
  File "/home/v-zhikangniu/miniconda3/envs/dac/lib/python3.9/site-packages/audiotools/ml/decorators.py", line 107, in decorated
    output = fn(*args, **kwargs)
  File "/home/v-zhikangniu/miniconda3/envs/dac/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/v-zhikangniu/descript-audio-codec/scripts/train.py", line 220, in val_loop
    "loss": state.mel_loss(recons, signal),
  File "/home/v-zhikangniu/miniconda3/envs/dac/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/v-zhikangniu/miniconda3/envs/dac/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/v-zhikangniu/descript-audio-codec/dac/nn/loss.py", line 322, in forward
    loss += self.log_weight * self.loss_fn(
  File "/home/v-zhikangniu/miniconda3/envs/dac/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/v-zhikangniu/miniconda3/envs/dac/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/v-zhikangniu/miniconda3/envs/dac/lib/python3.9/site-packages/torch/nn/modules/loss.py", line 101, in forward
    return F.l1_loss(input, target, reduction=self.reduction)
  File "/home/v-zhikangniu/miniconda3/envs/dac/lib/python3.9/site-packages/torch/nn/functional.py", line 3308, in l1_loss
    expanded_input, expanded_target = torch.broadcast_tensors(input, target)
  File "/home/v-zhikangniu/miniconda3/envs/dac/lib/python3.9/site-packages/torch/functional.py", line 76, in broadcast_tensors
    return _VF.broadcast_tensors(tensors)  # type: ignore[attr-defined]
RuntimeError: The size of tensor a (15000) must match the size of tensor b (15001) at non-singleton dimension 3

**Comment by ZhikangNiu** [comment]
here are my python package
```shell
Package                   Version         Editable project location
------------------------- --------------- ---------------------------------------
absl-py                   2.1.0
anyio                     4.3.0
argbind                   0.3.7
argon2-cffi               23.1.0
argon2-cffi-bindings      21.2.0
arrow                     1.3.0
asttokens                 2.4.1
async-lru                 2.0.4
attrs                     23.2.0
audioread                 3.0.1
Babel                     2.14.0
beautifulsoup4            4.12.3
bleach                    6.1.0
certifi                   2024.2.2
cffi                      1.16.0
charset-normalizer        3.3.2
comm                      0.2.1
contourpy                 1.2.0
coverage                  7.4.2
cycler                    0.12.1
debugpy                   1.8.1
decorator                 5.1.1
defusedxml                0.7.1
descript-audio-codec      1.0.0           /home/v-zhikangniu/descript-audio-codec
descript-audiotools       0.7.2
docstring-parser          0.15
einops                    0.7.0
encodec                   0.1.1
exceptiongroup            1.2.0
executing                 2.0.1
fastjsonschema            2.19.1
ffmpy                     0.3.2
filelock                  3.13.1
fire                      0.5.0
flatten-dict              0.4.2
fonttools                 4.49.0
fqdn                      1.5.1
fsspec                    2024.2.0
future                    1.0.0
grpcio                    1.62.0
h11                       0.14.0
httpcore                  1.0.4
httpx                     0.27.0
idna                      3.6
importlib-metadata        7.0.1
importlib-resources       6.1.1
iniconfig                 2.0.0
ipykernel                 6.29.2
ipython                   8.18.1
isoduration               20.11.0
jedi                      0.19.1
Jinja2                    3.1.3
joblib                    1.3.2
json5                     0.9.17
jsonpointer               2.4
jsonschema                4.21.1
jsonschema-specifications 2023.12.1
julius                    0.2.7
jupyter_client            8.6.0
jupyter_core              5.7.1
jupyter-events            0.9.0
jupyter-lsp               2.2.2
jupyter_server            2.12.5
jupyter_server_terminals  0.5.2
jupyterlab                4.1.2
jupyterlab_pygments       0.3.0
jupyterlab_server         2.25.3
kiwisolver                1.4.5
lazy_loader               0.3
librosa                   0.10.1
llvmlite                  0.42.0
Markdown                  3.5.2
markdown-it-py            3.0.0
markdown2                 2.4.12
MarkupSafe                2.1.5
matplotlib                3.8.3
matplotlib-inline         0.1.6
mdurl                     0.1.2
mistune                   3.0.2
mpmath                    1.3.0
msgpack                   1.0.7
nbclient                  0.9.0
nbconvert                 7.16.1
nbformat                  5.9.2
nest-asyncio              1.6.0
networkx                  3.2.1
notebook_shim             0.2.4
numba                     0.59.0
numpy                     1.26.4
nvidia-cublas-cu12        12.1.3.1
nvidia-cuda-cupti-cu12    12.1.105
nvidia-cuda-nvrtc-cu12    12.1.105
nvidia-cuda-runtime-cu12  12.1.105
nvidia-cudnn-cu12         8.9.2.26
nvidia-cufft-cu12         11.0.2.54
nvidia-curand-cu12        10.3.2.106
nvidia-cusolver-cu12      11.4.5.107
nvidia-cusparse-cu12      12.1.0.106
nvidia-nccl-cu12          2.19.3
nvidia-nvjitlink-cu12     12.3.101
nvidia-nvtx-cu12          12.1.105
onnx                      1.12.0
onnx-simplifier           0.4.35
overrides                 7.7.0
packaging                 23.2
pandas                    2.2.0
pandocfilters             1.5.1
parso                     0.8.3
pesq                      0.0.4
pexpect                   4.9.0
pillow                    10.2.0
pip                       23.3.1
platformdirs              4.2.0
pluggy                    1.4.0
pooch                     1.8.1
prometheus_client         0.20.0
prompt-toolkit            3.0.43
protobuf                  3.19.6
psutil                    5.9.8
ptyprocess                0.7.0
pure-eval                 0.2.2
pycparser                 2.21
Pygments                  2.17.2
pyloudnorm                0.1.1
pynvml                    11.5.0
pyparsing                 3.1.1
pystoi                    0.4.1
pytest                    8.0.1
pytest-cov                4.1.0
python-dateutil           2.8.2
python-json-logger        2.0.7
pytz                      2024.1
PyYAML                    6.0.1
pyzmq                     25.1.2
randomname                0.2.1
referencing               0.33.0
requests                  2.31.0
rfc3339-validator         0.1.4
rfc3986-validator         0.1.1
rich                      13.7.0
rpds-py                   0.18.0
scikit-learn              1.4.1.post1
scipy                     1.12.0
seaborn                   0.13.2
Send2Trash                1.8.2
setuptools                68.2.2
six                       1.16.0
sniffio                   1.3.0
soundfile                 0.12.1
soupsieve                 2.5
soxr                      0.3.7
stack-data                0.6.3
sympy                     1.12
tabulate                  0.9.0
tensorboard               2.16.2
tensorboard-data-server   0.7.2
termcolor                 2.4.0
terminado                 0.18.0
threadpoolctl             3.3.0
tinycss2                  1.2.1
tomli                     2.0.1
torch                     2.2.0
torch-stoi                0.2.1
torchaudio                2.2.0
tornado                   6.4
tqdm                      4.66.2
traitlets                 5.14.1
triton                    2.2.0
types-python-dateutil     2.8.19.20240106
typing_extensions         4.9.0
tzdata                    2024.1
uri-template              1.3.0
urllib3                   2.2.1
watchdog                  4.0.0
wcwidth                   0.2.13
webcolors                 1.13
webencodings              0.5.1
websocket-client          1.7.0
Werkzeug                  3.0.1
wheel                     0.41.2
zipp                      3.17.0
```

**Comment by ZhikangNiu** [comment]
And I follow this pr, it can works well https://github.com/descriptinc/descript-audio-codec/pull/44
