### ISSUE TITLE
pip install visqol?

### ISSUE THREAD

**Issue by a897456** [descriptinc/descript-audio-codec#85]
I am sorry. I'm a beginner. Excuse me. I want to ask a question.
### then 
  File "E:\ProgramData\anaconda3\envs\py39DAC\lib\site-packages\audiotools\metrics\quality.py", line 126, in visqol
    from visqol import visqol_lib_py
ModuleNotFoundError: No module named 'visqol'
### then  pip install visqol
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
ERROR: Could not find a version that satisfies the requirement visqol (from versions: none)
ERROR: No matching distribution found for visqol

**Comment by a897456** [comment]
### Then,
https://github.com/google/visqol?tab=readme-ov-file#linuxmac-build-instructions
### I think VISQOL has been installed successfully.
Target //:visqol up-to-date:
  bazel-bin/visqol
INFO: Elapsed time: 69.243s, Critical Path: 32.49s
INFO: 832 processes: 4 internal, 828 local.
INFO: Build completed successfully, 832 total actions
(py311) zh@zh-ThinkStation-P360-Tower:~/00/visqol-master$ cd ..
### So, I try again:
(py311) zh@zh-ThinkStation-P360-Tower:~/00/descript-audio-codec-main/scripts$ python evaluate.py

concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/zh/anaconda3/envs/py311/lib/python3.11/concurrent/futures/process.py", line 261, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zh/00/descript-audio-codec-main/scripts/evaluate.py", line 38, in get_metrics
    f"visqol-audio-{k}": metrics.quality.visqol(x, y),
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zh/anaconda3/envs/py311/lib/python3.11/site-packages/audiotools/metrics/quality.py", line 126, in visqol
    from visqol import visqol_lib_py
ModuleNotFoundError: No module named 'visqol'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zh/00/descript-audio-codec-main/scripts/evaluate.py", line 105, in <module>
    evaluate()
  File "/home/zh/anaconda3/envs/py311/lib/python3.11/site-packages/argbind/argbind.py", line 159, in cmd_func
    return func(*cmd_args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zh/anaconda3/envs/py311/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/zh/00/descript-audio-codec-main/scripts/evaluate.py", line 92, in evaluate
    keys = list(futures[0].result().keys())
                ^^^^^^^^^^^^^^^^^^^
  File "/home/zh/anaconda3/envs/py311/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/zh/anaconda3/envs/py311/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
ModuleNotFoundError: No module named 'visqol'
### What? oh no

**Comment by xjf-303** [comment]
我注意到你已经解决了这个visqol的安装问题，但是我仍然卡在

ERROR: /mnt/data/user/fan_xiaoran/xjf/metrics/visqol/BUILD:83:11: //:visqol_lib depends on @armadillo_headers//:armadillo_header in repository @armadillo_headers which failed to fetch. no such package '@armadillo_headers//': java.io.IOException: Error downloading [http://sourceforge.net/projects/arma/files/armadillo-10.6.0.tar.xz] to /root/.cache/bazel/_bazel_root/4daf52b73e561e0ddce4d8773e232c31/external/armadillo_headers/temp1097671164740017820/armadillo-10.6.0.tar.xz: connect timed out

这一步，我按照一些经验将workspace中已经弃用的9.900.1版本更改成了10.6.0版本，并且手动下载复制到指定目录，但是报如上错误

请教一下（在实验室ubuntu服务器上进行配置）
